library(rpart)
train=read.csv('../data/train.csv')
test=read.csv('../data/test.csv')
sapply(training,class)
fit<-rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
           data=train, method='class')
plot(fit)
text(fit)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(fit,cex=0.8)
prediction<-predict(fit,test,type='class')
df3<-data.frame(PassengerId=test$PassengerId,Survived=prediction)
write.csv(df3,'rpart_mod.csv',row.names = FALSE)